#!/bin/sh
# mkquot.sh,v

echo '(* file generated by mkquot.sh: do not edit! *)'
echo
../meta/camlp5r -nolib -I ../meta ../etc/pa_mktest.cmo ../meta/pa_macro.cmo ../etc/pr_r.cmo \
	-pa_mktest-ignore-type class_infos \
	-pa_mktest-expand-type generic_constructor \
	-flag D -sep '\n' -impl ../main/mLast.mli
