#!/bin/sh
# $Id: htmlp2html,v 1.4 2007/07/19 02:26:13 deraugla Exp $

FILE=$1

(
  echo '<div id="tableofcontents">'
  echo '  <ol>'
  grep '<h[23]>' $FILE |
  sed -e 's|^<h2>\(.*\)</h2>|b2<a href="#\1">\1</a>e2|' |
  sed -e 's|^<h3>\(.*\)</h3>|b3<a href="#\1">\1</a>e3|' |
  sed -e '{:b N; s/\n//; tb}' |
  sed -e 's/e2b3/\n      <ul>\n        <li>/g' |
  sed -e 's|e3b2|</li>\n      </ul>\n    </li>\n    <li>|g' |
  sed -e 's/b2/    <li>/g' |
  sed -e 's|e2|</li>\n|g' |
  sed -e 's|e3b3|</li>\n        <li>|g' |
  sed -e 's|e3|</li>\n      </ul>\n    </li>|g'
  echo '  </ol>'
  echo '</div>'
) > toc.tmp

cat $FILE |
sed \
  -e '/<div id="menu">/i\aaa' \
  -e '/<div id="menu">/,/^<\/div>/d' |
sed -e '/aaa/r menu.html' -e '/aaa/d' |
sed \
  -e '/<div id="tableofcontents">/i\aaa' \
  -e '/<div id="tableofcontents">/,/^<\/div>/d' |
sed -e '/aaa/r toc.tmp' -e '/aaa/d' |
sed \
  -e '/<div class="trailer">/i\aaa' \
  -e '/<div class="trailer">/,/^<\/div>/d' |
sed -e '/aaa/r trailer.html' -e '/aaa/d' |
sed -e '/<h2>/s|<h2>\(.*\)</h2>|<a id="\1"></a><h2>\1</h2>|' |
sed -e '/<h3>/s|<h3>\(.*\)</h3>|<a id="\1"></a><h3>\1</h3>|'

# rm toc.tmp
