#!/bin/sh
# $Id: html2texi,v 1.2 2007/08/26 21:39:55 deraugla Exp $

FILES1="index.html ptools.html"
FILES2="parsers.html lexers.html fparsers.html grammars.html"
FILES3="printers.html pretty.html"
FILES4="locations.html ml_ast.html pcaml.html syntext.html opretty.html quot.html revsynt.html scheme.html macros.html pragma.html extfun.html"
FILES5="conclusion.html"
FILES6="commands.html library.html sources.html"
FILES="$FILES1 $FILES2 $FILES3 $FILES4 $FILES5 $FILES6"
VERSION="$(grep "value version =" ../../main/pcaml.ml | sed -e 's/^[^"]*"\([^"]*\).*$/\1/')"

/bin/echo '\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename camlp5.info'
/bin/echo "@settitle Camlp5 manual $VERSION"
/bin/echo '@c %**end of header'

/bin/echo '
@titlepage
@title Camlp5 manual
@author Daniel de Rauglaudre
@end titlepage'

/bin/echo '
@node Top
@top Camlp5: a preprocessor pretty printer for OCaml'

/bin/echo '
@menu
* Overview::
* Parsing Tools::
* Printing Tools::
* Language extensions::
* Conclusion::
* Appendix::
@end menu'

/bin/echo '
@node Overview
@unnumbered Overview

@menu
* Introduction::
* Parsing and Printing tools::
@end menu'

for i in $FILES1; do
  N=$(grep '<h1' $i | sed -e 's|<h1[^>]*>||' -e 's|</h1>||')
  /bin/echo "
@node $N
@chapter $N"
  cat $i
done

/bin/echo '
@bye'
