#!/bin/sh
# $Id: html2texi,v 1.11 2007/08/28 03:22:04 deraugla Exp $

FILES1="index.html ptools.html"
FILES2="parsers.html lexers.html fparsers.html grammars.html"
FILES3="printers.html pretty.html"
FILES4="locations.html ml_ast.html pcaml.html syntext.html opretty.html quot.html revsynt.html scheme.html macros.html pragma.html extfun.html"
FILES5="conclusion.html"
FILES6="commands.html library.html sources.html"
FILES="$FILES1 1 $FILES2 2 $FILES3 3 $FILES4 4 $FILES5 5 $FILES6"
VERSION="$(grep "value version =" ../../main/pcaml.ml | sed -e 's/^[^"]*"\([^"]*\).*$/\1/')"

/bin/echo '\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename camlp5.info'
/bin/echo "@settitle Camlp5 manual $VERSION"
/bin/echo '@c %**end of header'

/bin/echo '
@titlepage
@title Camlp5 manual
@author Daniel de Rauglaudre
@end titlepage'

/bin/echo '
@node Top
@top Camlp5: a preprocessor pretty printer for OCaml'

/bin/echo '
@menu'

(
  /bin/echo 'sed \'
  for i in $FILES; do
    if [ "$i" = "1" ]; then
      :
    elif [ "$i" = "2" ]; then
      :
    elif [ "$i" = "3" ]; then
      :
    elif [ "$i" = "4" ]; then
      :
    elif [ "$i" = "5" ]; then
      :
    else
      N=$(grep '<h1' $i | sed -e 's|<h1[^>]*>||' -e 's|</h1>||')
      /bin/echo "  -e 's/@pxref{$i}/@pxref{$N}/' \\"
    fi
  done
  /bin/echo
) > tmp

for i in $FILES; do
  if [ "$i" = "1" ]; then
    /bin/echo
    /bin/echo 'Parsing Tools'
    /bin/echo
  elif [ "$i" = "2" ]; then
    /bin/echo
    /bin/echo 'Printing Tools'
    /bin/echo
  elif [ "$i" = "3" ]; then
    /bin/echo
    /bin/echo 'Language extensions'
    /bin/echo
  elif [ "$i" = "4" ]; then
    /bin/echo
    /bin/echo 'Conclusion'
    /bin/echo
  elif [ "$i" = "5" ]; then
    /bin/echo
    /bin/echo 'Appendix'
    /bin/echo
  else
    N=$(grep '<h1' $i | sed -e 's|<h1[^>]*>||' -e 's|</h1>||')
    /bin/echo "* $N::"
  fi
done

/bin/echo '
@end menu'

/bin/echo

chapter=chapter

for i in $FILES; do
  if [ "$i" = "1" ]; then
    :
  elif [ "$i" = "2" ]; then
    :
  elif [ "$i" = "3" ]; then
    :
  elif [ "$i" = "4" ]; then
    :
  elif [ "$i" = "5" ]; then
    chapter=appendix
  else
    N=$(grep '<h1' $i | sed -e 's|<h1[^>]*>||' -e 's|</h1>||')
    /bin/echo "
@node $N
@$chapter $N"
    cat $i |
    sed \
      -e 's|</p>|\n</p>|' \
      -e 's|\([^ ]\)</li>|\1\n</li>|g' \
      -e 's|\([^ ]\)</dd>|\1\n</dd>|g' \
      -e '/<pre[^>]*>/,/<\/pre>/s/ /~~/g' |
    sed \
      -e '/<p>/,/<\/p>/s/^ *//' \
      -e '/<li>/,/^ <\/li>/s/^ *//' \
      -e '/<dd>/,/<\/dd>/s/^ *//' \
      -e '/<div[^>]*>/,/<\/div>/s/^ *//' \
      -e '/<pre[^>]*>/,/<\/pre>/s/~~/ /g' |
    sed \
      -e '{/<table[^>]*>$/N; :b; /<tr>$/N; s/\n *//; tb; /<\/tr>$/N; s/\n *//; tb; /<\/th>$/N; s/\n *//; tb; /<\/td>$/N; s/\n *//; tb; /<thead>$/N; s/\n *//; tb; /<\/thead>$/N; s/\n *//; tb; /<tbody>$/N; s/\n *//; tb; /<\/tbody>$/N; s/\n *//; tb}' |
    sed \
      -e 's|@|@@|g' \
      -e 's|{|@{|g' -e 's|}|@}|g' \
      -e '/<div id="tableofcontents">/,/<\/div>/d' \
      -e '/<div class="trailer">/,$d' \
      -e 's|<div[^>]*>|@noindent |' -e 's|</div>||' \
      -e '1,/<h1/d' \
      -e 's|<h2>|@section |' -e 's|</h2>||' \
      -e 's|<h3>|@subsection |' -e 's|</h3>||' \
      -e 's|<h4>|@subsubsection |' -e 's|</h4>||' \
      -e '/<pre>/,/<\/pre>/s/^  //' \
      -e 's|<br/>|\n\n@noindent |g' \
      -e 's|^ *<p>|@noindent |' -e 's|</p>||' \
      -e 's|^ *<ul>|@itemize|' -e 's|^ *</ul>|@end itemize|' \
      -e 's|^ *<ol>|@enumerate|' -e 's|^ *</ol>|@end enumerate|' \
      -e 's|^ *<li>|@item |' -e '/<\/li>/d' \
      -e 's|^ *<dl><dd>|@quotation |' -e 's|^ *</dd></dl>|@end quotation|' \
      -e 's|^ *<dl>|@table @asis|' -e 's|^ *</dl>|@end table|' \
      -e 's|^ *<dt>|@item |' -e 's|</dt>||' \
      -e 's|^ *<dd>||' -e '/<\/dd>/d' \
      -e 's|<b>|@strong{|g' -e 's|</b>|}|g' \
      -e 's|<em>|@emph{|g' -e 's|</em>|}|g' \
      -e 's|<tt>||g' -e 's|</tt>||g' \
      -e 's|<code>||g' -e 's|</code>||g' \
      -e 's|<span [^>]*>|@emph{|g' -e 's|</span>|}|g' \
      -e 's|<a href=\"\([^.]*.html\)[^>]*>|(@pxref{\1}) |g' -e 's|</a>||g' \
      -e 's|<a [^>]*>||g' \
      -e 's|<pre>|@exampleindent 5\n@example|' -e 's|</pre>|@end example|' \
      -e 's|<pre [^>]*>|@exampleindent 0\n@example|' \
      -e 's|<table border="1">|@multitable @columnfractions .35 .35 .23\n|' \
      -e 's|<table[^>]*>|\n@multitable @columnfractions .50 .50\n|' \
      -e 's|</table>|@end multitable|' \
      -e 's|<tr><th[^>]*>|@headitem |g' -e 's|</th><th[^>]*>| @tab |g' \
      -e 's|</th></tr>|\n|g' \
      -e 's|<tr><td>|@item |g' -e 's|</td><td[^>]*>| @tab |g' \
      -e 's|</td></tr>|\n|g' \
      -e 's/&lt;/</g' -e 's/&gt;/>/g' -e 's/&nbsp;/ /g' -e 's/&amp;/\&/g'
  fi
done |
sh ./tmp

/bin/echo '
@bye'
