
WD=$(shell pwd)
TOP=../..

DESTDIR=
RM=rm

LAUNCH=env TOP=$(TOP) ocamlfind camlp5-buildscripts/LAUNCH --
YAWRAP=ocamlfind camlp5-buildscripts/ya-wrap-ocamlfind
OCAMLFIND=ocamlfind
NOT_OCAMLFIND=not-ocamlfind
SYNTAX := camlp5o
PACKAGES := camlp5