(* camlp5r *)
(* File generated by program: edit only if it does not compile. *)

val usage :
  (string * Arg.spec * string) list -> (string * Arg.spec * string) list ->
    unit;;

val parse :
  (string * Arg.spec * string) list -> (string -> unit) -> string list ->
    string list;;
