(* camlp5r *)
(***********************************************************************)
(*                                                                     *)
(*                             Camlp5                                  *)
(*                                                                     *)
(*                Daniel de Rauglaudre, INRIA Rocquencourt             *)
(*                                                                     *)
(*  Copyright 2007 Institut National de Recherche en Informatique et   *)
(*  Automatique.  Distributed only by permission.                      *)
(*                                                                     *)
(***********************************************************************)

(* This file has been generated by program: do not edit! *)

val fast : bool ref;;
val no_constructors_arity : bool ref;;
val mkloc : Stdpp.location -> Location.t;;
val long_id_of_string_list : Stdpp.location -> string list -> Longident.t;;

val str_item : MLast.str_item -> Parsetree.structure -> Parsetree.structure;;
val interf : string -> MLast.sig_item list -> Parsetree.signature;;
val implem : string -> MLast.str_item list -> Parsetree.structure;;
val phrase : MLast.str_item -> Parsetree.toplevel_phrase;;
