(* camlp5r *)
(* This file has been generated by program: do not edit! *)
(* Copyright (c) INRIA 2007 *)

val interf : string -> MLast.sig_item list -> Parsetree.signature;;
val implem : string -> MLast.str_item list -> Parsetree.structure;;
val phrase : MLast.str_item -> Parsetree.toplevel_phrase;;

val mkloc : Stdpp.location -> Location.t;;

val fast : bool ref;;
val no_constructors_arity : bool ref;;
