(* camlp5r *)
(***********************************************************************)
(*                                                                     *)
(*                             Camlp5                                  *)
(*                                                                     *)
(*                Daniel de Rauglaudre, INRIA Rocquencourt             *)
(*                                                                     *)
(*  Copyright 2007 Institut National de Recherche en Informatique et   *)
(*  Automatique.  Distributed only by permission.                      *)
(*                                                                     *)
(***********************************************************************)

(* This file has been generated by program: do not edit! *)

val patt : (MLast.loc -> MLast.loc) -> int -> MLast.patt -> MLast.patt;;
val expr : (MLast.loc -> MLast.loc) -> int -> MLast.expr -> MLast.expr;;
