(* camlp5r *)
(* This file has been generated by program: do not edit! *)
(* Copyright (c) INRIA 2007-2010 *)

open Parsetree;;
open Asttypes;;

val sys_ocaml_version : string;;

val ocaml_location : string * int * int * int * int -> Location.t;;

val ocaml_ptyp_poly : (string list -> core_type -> core_type_desc) option;;
val ocaml_type_declaration :
  string list -> (core_type * core_type * Location.t) list -> type_kind ->
    private_flag -> core_type option -> Location.t -> (bool * bool) list ->
    type_declaration;;
val ocaml_ptype_record :
  (string * mutable_flag * core_type * Location.t) list -> private_flag ->
    type_kind;;
val ocaml_ptype_variant :
  (string * core_type list * Location.t) list -> private_flag -> type_kind;;
val ocaml_ptype_private : type_kind;;
val ocaml_pwith_type :
  string list -> type_kind -> bool -> core_type option ->
    (bool * bool) list -> Location.t -> with_constraint;;

val module_prefix_can_be_in_first_record_label_only : bool;;

val ocaml_pexp_lazy : (expression -> expression_desc) option;;
val ocaml_const_int32 : (string -> constant) option;;
val ocaml_const_int64 : (string -> constant) option;;
val ocaml_const_nativeint : (string -> constant) option;;
val ocaml_pexp_object : (class_structure -> expression_desc) option;;

val ocaml_ppat_lazy : (pattern -> pattern_desc) option;;
val ocaml_ppat_record : (Longident.t * pattern) list -> pattern_desc;;

val ocaml_psig_recmodule :
  ((string * module_type) list -> signature_item_desc) option;;
val ocaml_pstr_recmodule :
  ((string * module_type * module_expr) list -> structure_item_desc) option;;

val ocaml_pctf_val :
  string * mutable_flag * core_type * Location.t -> class_type_field;;
val ocaml_pcf_inher : class_expr -> string option -> class_field;;
val ocaml_pcf_meth :
  string * private_flag * expression * Location.t -> class_field;;
val ocaml_pcf_val :
  string * mutable_flag * expression * Location.t -> class_field;;
val ocaml_pexp_poly :
  (expression -> core_type option -> expression_desc) option;;

val action_arg : string -> string list -> Arg.spec -> string list option;;
val arg_symbol : Arg.spec -> string list option;;
