#!/bin/bash

TOP=".."
export PATH=${TOP}/local-install/bin:${PATH}
export OCAMLPATH=${TOP}/local-install/lib:${OCAMLPATH}
OCAMLFIND=ocamlfind
CAMLP5LIB=`${OCAMLFIND} query camlp5`
CAMLP5="${TOP}/local-install/bin/camlp5r -I ${CAMLP5LIB}"

${CAMLP5} pa_r.cmo pa_rp.cmo pa_macro.cmo pa_extend.cmo pa_extend_m.cmo pa_macro_gram.cmo q_phony.cmo pr_r.cmo pr_ro.cmo pr_rp.cmo pr_extend.cmo -no-pa-opt $*
