#!/usr/bin/perl

{
  my @l = <STDIN> ;
  my $txt = join('', @l) ;

  $txt =~ s| *<dl(?:.*?)>(.*?)</dl>| doblock($1) |gse ;

  print $txt ;
}

sub doblock {
  my $s = shift ;
  
  my $ty ;
  if ($s =~ s|<dt>(.*?)</dt>||m) {
    $ty = $1 ;
  }
  my $acc = <<"EOF";
$ty

EOF
  while ($s =~ s%<tt style="color:(blue|red)">(.*?)``%%m) {
    $color = $1 ;
    $body = $2 ;
    $acc .= <<"EOF";
  - :${color}:`$body`
EOF
  }
  return $acc ;
}

sub stripnl {
  my $s = shift;
  $s =~ s,\n,,gs ;
  return $s 
}

sub striplws {
  my $s = shift;
  $s =~ s,\n *,\n,gs ;
  return $s 
}

sub header {
  my $pre = shift ;
  my $post = shift ;
  my $txt = shift ;
  my $len = length($txt) ;
  return  ($pre x $len) . "\n" . $txt . "\n" . ($post x $len) ;
}
