#!/usr/bin/perl

use Data::Dumper ;

{
  my @l = <ARGV> ;
  my $txt = join('', @l) ;
  $txt =~ s|<h1.*?>(.*?)</h1>| header("*","*",$1) |gme ;
  $txt =~ s|<h2>(.*?)</h2>| header("","=",$1) |gme ;
  $txt =~ s|<h3>(.*?)</h3>| header("","-",$1) |gme ;
  $txt =~ s|<h4>(.*?)</h4>| header("","^",$1) |gme ;
  $txt =~ s|<h4>(.*?)</h5>| header("",'"',$1) |gme ;

  $txt =~ s|"<tt>|``|gm ;
  $txt =~ s|</tt>"|``|gm ;

  $txt =~ s|<tt>|``|gm ;
  $txt =~ s|</tt>|``|gm ;

  $txt =~ s|"<code>|``|gm ;
  $txt =~ s|</code>"|``|gm ;

  $txt =~ s|<code>|``|gm ;
  $txt =~ s|</code>|``|gm ;

  $txt =~ s|<pre>|::\n|gm ;
  $txt =~ s|</pre>||gm ;

  $txt =~ s|&lt;|<|gm ;
  $txt =~ s|&gt;|>|gm ;

  $txt =~ s|<ul>||gm ;
  $txt =~ s|</ul>||gm ;

  $txt =~ s|( +)<li>(.*?)</li>| "-$1". stripnl($2) |gme ;
  $txt =~ s|<em>(.*?)</em>| "*". $1 . "*" |gse ;
  $txt =~ s|<p>(.*?)</p>| striplws($1) |gse ;

  $txt =~ s|<dl>(.*?)</dl>| reformat_dl($1) |gse ;

  print $txt;
}

sub reformat_dl {
  my $s = shift ;

  $s =~ s|\s*<dt>(.*?)</dt>\s*<dd>(.*?)</dd>| reformat_dt_dd($1, $2) |gse ;

  return $s;
}

sub reformat_dt_dd {
  my $dt = shift ;
  my $dd = shift ;

  $dd =~ s,^\s*,,gm ;
  $dd =~ s,^,  ,gm ;

  my $s = <<"EOF";
- $dt

$dd

EOF
}

sub stripnl {
  my $s = shift;
  $s =~ s,\n,,gs ;
  return $s 
}

sub striplws {
  my $s = shift;
  $s =~ s,\n *,\n,gs ;
  return $s 
}

sub header {
  my $pre = shift ;
  my $post = shift ;
  my $txt = shift ;
  my $len = length($txt) ;
  return  ($pre x $len) . "\n" . $txt . "\n" . ($post x $len) ;
}
