(* camlp5r *)
(* This file has been generated by program: do not edit! *)
(* Copyright (c) INRIA 2007 *)

type 'a t;;

type ('bef, 'aft) gen_context =
  { ind : int; bef : 'bef; aft : 'aft; dang : string }
;;
type pr_context = (string, string) gen_context;;

val make : string -> 'a t;;

val apply : 'a t -> pr_context -> 'a -> string;;
val apply_level : 'a t -> string -> pr_context -> 'a -> string;;

val clear : 'a t -> unit;;

(**/**)

(* for system use *)

type position =
    First
  | Last
  | Before of string
  | After of string
  | Level of string
;;

type 'a pr_fun = pr_context -> 'a -> string;;

type 'a pr_rule =
  ('a, 'a pr_fun -> 'a pr_fun -> pr_context -> string) Extfun.t
;;

val extend :
  'a t -> position option ->
    (string option * ('a pr_rule -> 'a pr_rule)) list -> unit;;
