name: CI-DEBUG

# on: [push, pull_request]

on: [workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      # Test Linux, macOS and Windows with the oldest and newest supported OCaml
      # and trunk.
      matrix:
        os:
          - windows-latest
        ocaml-version:
          - "5.3"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set-up OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}

      - name: Setup Dependencies
        run: |
          opam pin add camlp5-buildscripts https://github.com/camlp5/camlp5-buildscripts.git
          opam install . --deps-only --with-doc --with-test
          opam pin add camlp5 . --no-action

      - name: Install it with opam
        run: |
          opam install -v -j 1 -t --strict camlp5

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: testsuite/*

      - name: Archive local-install
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: local-install
          path: |
            D:/a/camlp5/camlp5/_opam/.opam-switch/build/camlp5.8.03.04/local-install/bin/*
            D:/a/camlp5/camlp5/_opam/.opam-switch/build/camlp5.8.03.04/local-install/lib/*/*
