name: CI-DEBUG

# on: [push, pull_request]

on: [workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      # Test Linux, macOS and Windows with the oldest and newest supported OCaml
      # and trunk.
      matrix:
        os:
          - windows-latest
        ocaml-version:
          - "5.3"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set-up OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}

      - name: Setup Dependencies
        run: |
          opam install . --deps-only --with-doc --with-test
          opam pin add camlp5 . --no-action

      - name: build it all with make
        run: |
          ./configure
	  make all world.opt
	  make -C test clean all
	  make -C testsuite clean all-tests
	  make clean

      - name: Install it with opam
        run: |
          opam install -t --strict camlp5
